### PR TITLE
Add all the missing key words for moose tests files

### PR DESCRIPTION
**Pull request by GiudGiud**
If there's style guides for cson files, I imagine this is breaking them.

refs #10

### CODE REVIEW

**Comment by GiudGiud** [comment]
@dschwen can I please get a review on this

**Review by dschwen — APPROVED** [review]

**Comment by dschwen** [comment]
Neat, sorry, I didn't see this earlier!

**Comment by dschwen** [comment]
Publishing language-moose@v1.5.0 ✓

**Comment by GiudGiud** [comment]
you sure you don't want to merge the other one before publishing?

**Comment by dschwen** [comment]
Oh, D'Oh, another one...

**Pull request merged**
